--Trigger que impide la inserción de un menor si la edad no está comprendida entre 7 y 13
CREATE TRIGGER VALIDAREDAD BEFORE INSERT ON MENOR FOR EACH ROW
DECLARE
	ANYO NUMBER(4);
BEGIN
		SELECT EXTRACT(YEAR FROM SYSDATE) INTO ANYO
		FROM DUAL;
		IF ANYO - EXTRACT(YEAR FROM TO_DATE(:NEW.FECH_NAC,'DD/MM/YYYY')) NOT BETWEEN 7 AND 13 THEN
			RAISE_APPLICATION_ERROR(-200001, 'EDAD NO VALIDA PARA QUE UN MENOR PARTICIPE');
		ELSE
			COMMIT;
		END IF;
EXCEPTION
		WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('ERROR EN EL TRIGGER VALIDAREDAD');
		
END VALIDAREDAD;
/
