REM Creamos la secuencia necesaria para los insert into.
DROP SEQUENCE SMUNICIPIO;
CREATE SEQUENCE SMUNICIPIO
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE MUNICIPIO (
	ID_MUNICIPIO		NUMBER(3) NOT NULL,
	NOMBRE_MUNICIPIO	VARCHAR2(100) NOT NULL,
	ID_PROVINCIA		NUMBER(2) NOT NULL,
	CONSTRAINT PK_IDMUN_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO),
	CONSTRAINT FK_ID_PROVIN_PROV FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA),
	CONSTRAINT NOMBRE_REPETIDO UNIQUE (NOMBRE_MUNICIPIO)
)
/
--pause
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Alegría-Dulantzi', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Amurrio', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Añana', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aramaio', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Armiñón', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arraia-Maeztu', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arrazua-Ubarrundia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Artziniega', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Asparrena', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ayala/Aiara', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Baños de Ebro/Mañueta', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Barrundia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berantevilla', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bernedo', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Campezo/Kanpezu', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elburgo/Burgelu', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elciego', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elvillar/Bilar', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Harana/Valle de Arana', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Iruña Oka/Iruña de Oca', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Iruraiz-Gauna', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Kripan', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Kuartango', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Labastida/Bastida', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lagrán', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Laguardia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lanciego/Lantziego', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lantarón', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lapuebla de Labarca', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Laudio/Llodio', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Legutiano', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Leza', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Moreda de Álava', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Navaridas', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Okondo', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Oyón-Oion', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Peñacerrada-Urizaharra', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ribera Alta', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ribera Baja/Erribera Beitia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Salvatierra/Agurain', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Samaniego', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'San Millán/Donemiliaga', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Urkabustaiz', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Valdegovía/Gaubea', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Villabuena de Álava/Eskuernaga', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Vitoria-Gasteiz', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Yécora/Iekora', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zalduondo', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zambrana', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zigoitia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zuia', 1)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Abadiño', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Abanto y Ciérvana-Abanto Zierbena', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ajangiz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Alonsotegi', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Amorebieta-Etxano', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Amoroto', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arakaldo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arantzazu', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Areatza', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arrankudiaga', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arratzu', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arrieta', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arrigorriaga', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Artea', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Artzentales', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Atxondo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aulesti', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bakio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Balmaseda', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Barakaldo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Barrika', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Basauri', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bedia', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berango', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bermeo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berriatua', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berriz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bilbao', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Busturia', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Derio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Dima', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Durango', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ea', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elantxobe', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elorrio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Erandio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ereño', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ermua', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Errigoiti', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Etxebarri', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Etxebarria', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Forua', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Fruiz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Galdakao', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Galdames', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gamiz-Fika', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Garai', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gatika', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gautegiz Arteaga', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gernika-Lumo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Getxo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gizaburuaga', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gordexola', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gorliz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Güeñes', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ibarrangelu', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Igorre', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ispaster', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Iurreta', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Izurtza', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Karrantza Harana/Valle de Carranza', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Kortezubi', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lanestosa', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Larrabetzu', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Laukiz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Leioa', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lekeitio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lemoa', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lemoiz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lezama', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Loiu', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mallabia', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mañaria', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Markina-Xemein', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Maruri-Jatabe', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mendata', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mendexa', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Meñaka', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Morga', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mundaka', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mungia', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Munitibar-Arbatzegi Gerrikaitz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Murueta', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Muskiz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Muxika', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Nabarniz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ondarroa', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Orozko', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ortuella', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Otxandio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Plentzia', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Portugalete', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Santurtzi', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Sestao', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Sondika', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Sopelana', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Sopuerta', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Sukarrieta', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Trucios-Turtzioz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ubide', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ugao-Miraballes', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Urduliz', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Urduña-Orduña', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Valle de Trápaga-Trapagaran', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zaldibar', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zalla', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zamudio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zaratamo', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zeanuri', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zeberio', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zierbena', 2)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Abaltzisketa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aduna', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aizarnazabal', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Albiztur', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Alegia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Alkiza', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Altzaga', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Altzo', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Amezketa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Andoain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Anoeta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Antzuola', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arama', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Aretxabaleta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Arrasate/Mondragón', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Asteasu', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Astigarraga', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ataun', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Azkoitia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Azpeitia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Baliarrain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Beasain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Beizama', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Belauntza', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berastegi', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bergara', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Berrobi', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Bidegoian', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Deba', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Donostia-San Sebastián', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Eibar', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elduain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elgeta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Elgoibar', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Errenteria', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Errezil', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Eskoriatza', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ezkio-Itsaso', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gabiria', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gaintza', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Gaztelu', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Getaria', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Hernani', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Hernialde', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Hondarribia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ibarra', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Idiazabal', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ikaztegieta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Irun', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Irura', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Itsasondo', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Larraul', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lasarte-Oria', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lazkao', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Leaburu', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Legazpi', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Legorreta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Leintz-Gatzaga', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lezo', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Lizartza', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mendaro', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mutiloa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Mutriku', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Oiartzun', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Olaberria', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Oñati', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ordizia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Orendain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Orexa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Orio', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Ormaiztegi', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Pasaia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Segura', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Soraluze/Placencia de las Armas', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Tolosa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Urnieta', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Urretxu', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Usurbil', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Villabona', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zaldibia', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zarautz', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zegama', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zerain', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zestoa', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zizurkil', 3)
/
INSERT INTO MUNICIPIO VALUES (SMUNICIPIO.NEXTVAL, 'Zumaia', 3)
/
COMMIT;