CREATE TABLE MUNICIPIO (
	ID_MUNICIPIO		NUMBER(3) NOT NULL,
	NOMBRE_MUNICIPIO	VARCHAR2(100) NOT NULL,
	ID_PROVINCIA		NUMBER(2) NOT NULL,
	CONSTRAINT PK_IDMUN_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO),
	CONSTRAINT FK_ID_PROVIN_PROV FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)
)
/
--pause