DROP SEQUENCE SSOLICITUD;
CREATE SEQUENCE SSOLICITUD
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE SOLICITUD (
	ID_SOLICITUD		NUMBER(4) NOT NULL,
	FECHA_INSCRIPCION	DATE NOT NULL,
	NUMERO_SOLICITUD	NUMBER(4) NOT NULL,
	ORDEN			NUMBER(4) NOT NULL,
	FECHA_CITA		DATE NOT NULL,
	HORA_CITA		DATE NOT NULL,
	ID_MENOR		NUMBER(4) NOT NULL,
	ID_TUTOR		NUMBER(4) NOT NULL,
	FECHA_SORTEO		DATE NOT NULL,
	CONSTRAINT PK_ID_SOL_SOLICITUD PRIMARY KEY (ID_SOLICITUD),
	CONSTRAINT FK_ID_MEN_MENOR FOREIGN KEY (ID_MENOR) REFERENCES MENOR (ID_MENOR),
	CONSTRAINT FK_ID_TUT_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR (ID_TUTOR),
	CONSTRAINT FK_FECH_SOR_SORTEO FOREIGN KEY (FECHA_SORTEO) REFERENCES SORTEO (FECHA_SORTEO)	
)
/
--pause
