DROP SEQUENCE SCENTRO_ESTUDIO;
CREATE SEQUENCE SCENTRO_ESTUDIO
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE CENTRO_ESTUDIO (
	ID_CENTRO	NUMBER(4) NOT NULL,
	NOMBRE_CENTRO	VARCHAR2(100) NOT NULL,
	ID_PROVINCIA	NUMBER(2) NOT NULL,
	CONSTRAINT PK_ID_CENTRO_CENTRO PRIMARY KEY (ID_CENTRO),
	CONSTRAINT FK_ID_PROVI_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)	
)
/
--pause
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEP A. LZ. De Guereñu LHI',1);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEP Abetxuko Ikastola LHI',1);   
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEP Abendaño Ikastola LHI',1);   
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEP Adurza Ikastola LHI',1);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEP Ángel Ganivet LHI',1);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEIP Arangoiti',2);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEIP Artatse',2);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEIP Basurto',2);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEIP Birjinetxe',2);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'CEIP Cervantes',2);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'Airete Lhi',3);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'Aitor Ikastola',3);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'Altza-S. J. C.',3);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'Amara Berri-morlans',3);
INSERT INTO CENTRO_ESTUDIO VALUES (SCENTRO_ESTUDIO.NEXTVAL,'Amasorrain Ikastola',3);
COMMIT;


