CREATE TABLE HOJA_INSCRIPCION (
	ID_MENOR	NUMBER(4) NOT NULL,
	ID_TUTOR	NUMBER(4) NOT NULL,
	NUMERO		NUMBER(8) NOT NULL,
	PISO		VARCHAR2(10) NOT NULL,
	CP		CHAR(5) NOT NULL,
	PROVINCIA	NUMBER(2) NOT NULL,
	CONSTRAINT PK_IDM_IDT_HOJ_INSCRIP PRIMARY KEY (ID_MENOR,ID_TUTOR),
	CONSTRAINT FK_ID_MENOR_MENOR FOREIGN KEY (ID_MENOR) REFERENCES MENOR (ID_MENOR),
	CONSTRAINT FK_ID_TUTOR_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR (ID_TUTOR)
)
/
--pause