DROP SEQUENCE SHOJA_INSCRIPCION;
CREATE SEQUENCE SHOJA_INSCRIPCION
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE HOJA_INSCRIPCION (
	ID_HOJA_INSCRIPCION	NUMBER(4) NOT NULL,
	ID_MENOR		NUMBER(4) NOT NULL,
	ID_TUTOR		NUMBER(4) NOT NULL,
	NUMERO			NUMBER(8) NOT NULL,
	PISO			VARCHAR2(10) NOT NULL,
	CP			CHAR(5) NOT NULL,
	PROVINCIA	NUMBER(2) NOT NULL,
	CONSTRAINT PK_ID_HOJA_HOJA PRIMARY KEY (ID_HOJA_INSCRIPCION),
	CONSTRAINT FK_ID_MENOR_MENOR FOREIGN KEY (ID_MENOR) REFERENCES MENOR (ID_MENOR),
	CONSTRAINT FK_ID_TUTOR_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR (ID_TUTOR)
)
/
--pause