DROP SEQUENCE STUTOR;
CREATE SEQUENCE STUTOR
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE TUTOR (
	ID_TUTOR	NUMBER(4) NOT NULL,
	NOMBRE		VARCHAR2(40) NOT NULL,
	APELLIDO1	VARCHAR2(40) NOT NULL,
	APELLIDO2	VARCHAR2(40) NOT NULL,
	DNI		CHAR(10) NOT NULL,
	TLF1		CHAR(9) NOT NULL,
	TLF2		CHAR(9),
	TLF3		CHAR(9),
	TLF4		CHAR(9),
	CONSTRAINT PK_ID_TUTOR_TUTOR PRIMARY KEY (ID_TUTOR),
	CONSTRAINT UNIQUE_DNI UNIQUE (DNI)
)
/
--pause