DROP SEQUENCE SCALLE;
CREATE SEQUENCE SCALLE
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE CALLE (
	ID_CALLE	NUMBER(4) NOT NULL,
	NOMBRE_CALLE	VARCHAR2(100) NOT NULL,
	ID_MUNICIPIO	NUMBER(3) NOT NULL,
	CONSTRAINT PK_ID_CALLE_CALLE PRIMARY KEY (ID_CALLE),
	CONSTRAINT FK_ID_MUN_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO)
)
/
--pause
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Agurain Kalea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Alegria',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Arrabal Kalea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Bide Zaharra Kalea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Agurain',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Alborkoin',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Añua Bidea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Anunzargarai',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Argomaniz Bidea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Arriaga Bidea',1);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Abiaga Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Abiagabarri Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Aiara Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Aldai Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Amurrio Entitatea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Arenalde Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Aresketa Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Bañuetaibar Kalea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Baranbio Entitatea',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Barrio de Berganza',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Barrio de San José',2);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Barrio de Abajo',3);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Barrio de Arriba',3);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Aita Gabirel Jauregi',4);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle de Matxain',4);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle del Puente',5);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle Real',5);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'CAMINO SIRISOLO/SIRISOLOBIDEA',6);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'CAMINO ZUMALDE BIDEA',6);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Barrio de Arriba',7);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Barrio de Ibaiartegui',7);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Artea Auzunea',8);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Arteko Aldapa',8);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Amamio Kalea',9);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Andoni Urrestarazu',9);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Aiara Kalea',10);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Aldai Kalea',10);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de la Serna',11);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Laguardia',11);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Barrio de Alkarana',12);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Barrio de Larrinzar',12);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Abajo',13);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Carretera',13);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Av de Izki', 14);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Abajo', 14);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'PLAZA SAMUEL PICAZA',15);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Potro Kalea',15);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle Arralde',16);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Abrevadero',16);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle Azalea',17);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Calle de Barco',17);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Bernedo Bidea',18);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL, 'Somillo Kalea',18);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle la Iglesia',19);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Calle Santa Cecilia',19);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Langariz Hiribidea',20);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Real Kalea',20);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Adriano VI.aren Kalea',46);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Adurtza Kalea',46);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Adiskidetasun Kalea',79);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Agirre Anaien Kalea',79);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'San Antonio Kalea',193);
INSERT INTO CALLE VALUES (SCALLE.NEXTVAL,'Barrio de Amara',193);
COMMIT;

























