REM Creamos una secuencia para que se ejecutando este archivo se genere la secuencia para los insert into
DROP SEQUENCE SPROVINCIA;
CREATE SEQUENCE SPROVINCIA
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
	
CREATE TABLE PROVINCIA (
	ID_PROVINCIA 		NUMBER(2) NOT NULL,
	NOMBRE_PROVINCIA	VARCHAR2(80) NOT NULL,
	CONSTRAINT PK_ID_PROV_PROVINCIA PRIMARY KEY (ID_PROVINCIA)
)
/
--pause
INSERT INTO PROVINCIA VALUES (SPROVINCIA.NEXTVAL, 'Alava/Araba')
/
INSERT INTO PROVINCIA VALUES (SPROVINCIA.NEXTVAL, 'Vizcaya/Bizkaia')
/
INSERT INTO PROVINCIA VALUES (SPROVINCIA.NEXTVAL, 'Guipuzcoa/Gipuzkoa')
/
COMMIT;