DROP SEQUENCE SCENTRO_ESTUDIO;
CREATE SEQUENCE SCENTRO_ESTUDIO
	MINVALUE 0
	START WITH 0
	INCREMENT BY 1
/
CREATE TABLE CENTRO_ESTUDIO (
	ID_CENTRO	NUMBER(4) NOT NULL,
	NOMBRE_CENTRO	VARCHAR2(100) NOT NULL,
	ID_PROVINCIA	NUMBER(2) NOT NULL,
	CONSTRAINT PK_ID_CENTRO_CENTRO PRIMARY KEY (ID_CENTRO),
	CONSTRAINT FK_ID_PROVI_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)	
)
/
--pause